"""Privacy disclosures served from the API.

The SPA renders /privacy, but the facts live here so the page cannot drift
from what the deployment actually does — in particular *which* third-party
LLM a self-hosted instance is shipping CV text to, which is an env var, not
a copywriting decision.
"""

from __future__ import annotations

from fastapi import APIRouter

from gosha.services.cv import MAX_CV_BYTES
from gosha.services.retention import retention_months

router = APIRouter(prefix="/legal", tags=["legal"])

# Kept next to the code that does the sending, so it is obvious when a new
# egress is added: gosha/cover_letter.py truncates the CV to CV_CHARS_TO_LLM
# characters and posts it to whichever provider gosha/llm.py selects.
_PROVIDER_DETAILS = {
    "deepseek": {
        "name": "DeepSeek API",
        "operator": "Hangzhou DeepSeek Artificial Intelligence Co., Ltd. (China)",
        "url": "https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html",
        "note": (
            "Requests are sent to DeepSeek's chat completions endpoint "
            "(model set by DEEPSEEK_MODEL) and processed in China."
        ),
    },
    "openrouter": {
        "name": "OpenRouter",
        "operator": "OpenRouter, Inc. (United States)",
        "url": "https://openrouter.ai/privacy",
        "note": (
            "OpenRouter routes the request on to the model vendor configured "
            "in OPENROUTER_MODEL."
        ),
    },
    "gemini": {
        "name": "Google Gemini API",
        "operator": "Google Ireland Ltd / Google LLC",
        "url": "https://ai.google.dev/gemini-api/terms",
        "note": "Requests are sent to the Gemini generateContent endpoint.",
    },
}


@router.get("/privacy")
async def privacy() -> dict:
    """Machine-readable privacy facts for the /privacy page."""
    from gosha.cover_letter import CV_CHARS_TO_LLM
    from gosha.llm import active_provider

    provider = _PROVIDER_DETAILS.get(active_provider(), {
        "name": "an external LLM provider",
        "operator": "unknown",
        "url": "",
        "note": "",
    })

    return {
        "controller": "GOSHA Jobs (gosha.bogdantruta.com)",
        "contact": "https://bogdantruta.com",
        "data_we_hold": [
            {
                "category": "Discord identity",
                "items": ["Discord user id", "username", "avatar URL"],
                "why": "To sign you in and to DM you job matches.",
                "source": "Discord OAuth, only after you approve it.",
            },
            {
                "category": "Your CV",
                "items": [
                    "the extracted plain text of the file you upload",
                    "a numeric embedding derived from it",
                ],
                "why": "To rank job postings against your actual skills.",
                "source": "You, when you upload it.",
            },
            {
                "category": "Activity",
                "items": [
                    "saved searches",
                    "jobs delivered to you and your thumbs up/down",
                    "applications you track",
                    "generated cover letters",
                    "page views (path only, no cross-site tracking)",
                ],
                "why": "To personalise the feed and run the product.",
                "source": "Your use of the site and the Discord bot.",
            },
        ],
        "third_party_processors": [
            {
                "name": "Discord",
                "operator": "Discord Netherlands BV / Discord Inc.",
                "receives": "your Discord id, and the job alerts we DM you",
                "url": "https://discord.com/privacy",
            },
            {
                "name": provider["name"],
                "operator": provider["operator"],
                "receives": (
                    f"up to {CV_CHARS_TO_LLM:,} characters of your CV text plus "
                    "the job posting, each time YOU ask for a cover letter"
                ),
                "url": provider["url"],
                "note": provider["note"],
            },
        ],
        "llm_disclosure": (
            "Cover letters are generated by a third-party model. When you "
            f"press 'Cover letter', up to {CV_CHARS_TO_LLM:,} characters of "
            f"your CV are sent to {provider['name']} together with the job "
            "description. This only happens on that explicit action — "
            "uploading a CV alone never sends it anywhere. If you would "
            "rather no external model ever saw your CV, do not use the "
            "cover-letter feature."
        ),
        "retention": {
            "cv_text": "Until you delete it or delete your account.",
            "cover_letters": (
                "Until you delete your account. Deleting your CV no longer "
                "leaves previously generated letters behind."
            ),
            "delivery_history": "Until you delete your account.",
            "events": "Until you delete your account.",
        },
        "your_rights": {
            "access_and_portability": "GET /api/v1/account/export",
            "erasure": "DELETE /api/v1/account?confirm=DELETE",
            "note": (
                "Erasure removes the account row, the CV file, cover "
                "letters, saved searches, delivery history, tracked "
                "applications and the event log. It cannot be undone."
            ),
        },
        "limits": {
            "cv_storage": (
                f"CVs are stored encrypted at rest on the server's disk (max "
                f"{MAX_CV_BYTES // (1024 * 1024)} MB per upload). The key is "
                "held by the running service, so this protects the disk and "
                "backups, not a compromised server. "
                + (
                    f"CVs of accounts inactive for {retention_months()} months "
                    "are deleted automatically."
                    if retention_months()
                    else "Automatic deletion of inactive CVs is turned off."
                )
            ),
            "third_party_assets": (
                "The landing page currently loads web fonts from Google and "
                "photography from Unsplash, which exposes your IP address to "
                "those providers. No third-party JavaScript runs on the site."
            ),
        },
    }
